### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by tangkun-github** [flyyuan/Chinese-Medical-QA-Data#1]
您好：

我下载的CSV文件，只有4KB，这是为什么呢

**Comment by flyyuan** [comment]
可能你链接有点问题。用这个 https://media.githubusercontent.com/media/flyyuan/Chinese-Medical-QA-Data/master/MedicalQAQA.csv

**Comment by tangkun-github** [comment]
新链接有数据了，谢谢您呀～
